### ISSUE TITLE
Error trying to create a new typescript project

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/generator-cheminfo#44]
I just updated the tools using `npm i --global yo generator-cheminfo`

I then tried to create a new project using `yo cheminfo:typescript` and I get the following error.

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @typescript-eslint/type-utils@5.10.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lpatiny/.npm/_logs/2022-01-19T07_45_00_667Z-debug.log

@targos an idea what I should do ?

**Comment by targos** [comment]
I don't know. I cannot reproduce this error:

```
> yo cheminfo:typescript
? ==========================================================================
We're constantly looking for ways to make yo better!
May we anonymously report usage statistics to improve the tool over time?
More info: https://github.com/yeoman/insight & http://yeoman.io
========================================================================== No
? Your project name xxx
? GitHub organization cheminfo
? Your name Michaël Zasso
? Your package description
? Is it a Node.js-only library? No
   create package.json
   create tsconfig.json
   create tsconfig.cjs.json
   create tsconfig.esm.json
   create .eslintrc.yml
   create jest.config.js
   create src\index.ts
   create src\__tests__\test.ts
   create src\.npmignore
   create .prettierrc.json
   create .npmrc
   create .gitignore
   create LICENSE
   create README.md

added 476 packages, and audited 477 packages in 13s

76 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by lpatiny** [comment]
Ok I end up doing `rm -rf .npm`. A little bit extreme but this worked.

Maybe [updating global packages](https://stackoverflow.com/questions/53238230/how-to-update-globally-installed-npm-packages) using `npm update -g` would also have worked.

**Comment by lpatiny** [comment]
Updating packages didn't work. I had to remove .npm again. Weird.
