### ISSUE TITLE
Can not create a new typescript project

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/generator-cheminfo#45]
I just did

`npm i --global yo generator-cheminfo``

And the try to create a new typescript project

`yo cheminfo:typescript`

But get the following error message during the install

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @typescript-eslint/type-utils@5.16.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lpatiny/.npm/_logs/2022-03-23T12_57_34_450Z-debug-0.log

@targos do you have an idea what is the problem and how I could solve it ?

**Comment by targos** [comment]
Seems to be a duplicate of https://github.com/cheminfo/generator-cheminfo/issues/44

**Comment by lpatiny** [comment]
Same problem same solution... Thanks ! Better somebody has some memory...
