### ISSUE TITLE
Question: updating migration guide

### ISSUE THREAD

**Issue by santimirandarp** [cheminfo/generator-cheminfo#52]
I'm following the ts-migration.md

1. I am not sure whether this lines / file is necessary

```javascript
module.exports = {
  presets: ['@babel/preset-typescript'],
  plugins: ['@babel/plugin-transform-modules-commonjs'],
};
```

As typescript does this by default.

2. Should we use Vitest instead of Jest ?

3. Should we use the zakodium typedoc.yml action instead of documentation js ?

-------------------

PS: I understand now that probably 1 and 3 are kept until the first migration is done.

**Comment by targos** [comment]
1. I believe it's necessary for Jest, which doesn't support TypeScript by default.
2. This is about migration to TypeScript. We don't want to introduce the complexity of migrating to a different test framework in this guide.
3. I'm not sure we can use typedoc.yml before all files are actually written in TS

**Comment by santimirandarp** [comment]
> 1. I believe it's necessary for Jest, which doesn't support TypeScript by default.
> 2. This is about migration to TypeScript. We don't want to introduce the complexity of migrating to a different test framework in this guide.

Yes. Using Vitest solves 1 and wouldn't need babel config, but it may not be worth the effort.

**Comment by targos** [comment]
It may be worth depending on the project. My point is it's out of scope for this guide to talk about unrelated refactorings.
