### ISSUE TITLE
Revert to node ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/generator-cheminfo#53]
If we create a TS project and `npm run test` we currently have the following error:

`error TS5110: Option 'module' must be set to 'Node16' when option 'moduleResolution' is set to 'Node16'.`

Coming from this line:

https://github.com/cheminfo/generator-cheminfo/blob/68653fa7b95ecde0314a377dbb9b50e0c59df6b3/generators/typescript/templates/tsconfig.json#L6

@targos Should we revert this code to `node` and not `node16`?

**Comment by targos** [comment]
sure
